version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: food
    ports:
      - "5434:5432"
  app:
    build:
      context: D:\repos\project-3
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5434
      DB_USER: postgres
      DB_PASSWORD: 123
    depends_on:
      - db
    ports:
      - "3000:5000"